### ISSUE TITLE
Mojave build issue

### ISSUE THREAD

**Issue by parcollet** [TRIQS/triqs#694] opened 2019-03-31 23:04 UTC
The install instructions do not work on Mojave.

Even worse, after installing llvm (8.0, same with 7.) with brew, 
even a simple trivial C code 
`#include <stdio.h>`
does not compile with error
`In file included from py.cpp:1:
/usr/local/opt/llvm/bin/../include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
#include_next <stdio.h>
`

This seems like a common issue : cf e.g
https://github.com/neovim/neovim/issues/9050

Adding 

> export SDKROOT=`xcrun --show-sdk-path`

seems to solve the issue.

Shall we fix this automatically in the Cmake ?

**Comment by parcollet** [comment] 2019-03-31 23:06
PS : It is due to the location of the include files.
There is a solution in the Release note of Apple, but it also says that
this package will not be present in future release. 
We need a more permanent solution, if possible.

**Comment by parcollet** [comment] 2019-03-31 23:16
PS : also the in the doc
brew install boost
we have to remote the --without-single 
which seems not to be supported any more

**Comment by Wentzell** [comment] 2019-04-02 15:22
Hi @parcollet,

Now that homebrew has removed the ```brew link``` functionality for any packages
that can clash with the system-provided software things are move tricky.

I was able to reproduce the problem on my machine and was able to install triqs
on OSX 10.14 (Mojave) by following the install intructions I have just pushed to https://triqs.github.io/triqs/unstable/installation/osx_install.html
Please have a look.

Can we close this issue?

**Comment by parcollet** [comment] 2019-04-02 18:12
It works for me. 
We should add back the brew formula. Where are they ? They were written for
brew science, which was closed when we submitted the PR,
but we could simply put it in our page and have a simpler instruction ?

**Comment by Wentzell** [comment] 2019-04-02 19:45
> We should add back the brew formula. Where are they ? They were written for
> brew science, which was closed when we submitted the PR,
> but we could simply put it in our page and have a simpler instruction ?

I updated the formula on unstable with the cleanest version of the PR that I did to homebrew-science
at some point. The commands to use it are
```bash
brew install https://raw.githubusercontent.com/TRIQS/triqs/unstable/packaging/os_x/triqs.rb
```
for the `2.1-rc1` version or
```bash
brew install https://raw.githubusercontent.com/TRIQS/triqs/unstable/packaging/os_x/triqs.rb --HEAD
```
for the master-branch.

It installs all dependencies without problems and compiles, but a number of python-tests fail.

@dylex Can we test the formula within the CI?

**Comment by Wentzell** [comment] 2020-08-11 20:12
We now recommend the use of anaconda packages for Mac OS. We do not provide a hombrew formula since homebrew science was discontinued.

**Closed by Wentzell** 2020-08-11 20:12 UTC
