### ISSUE TITLE
TypeError: Internal error : invalid id from h5py !

### ISSUE THREAD

**Issue by santoshkumarradha** [TRIQS/triqs#780] opened 2020-07-28 23:18 UTC
Hi, 
I had a fresh install from conda forge and I run into the error. I assume this is because of hdf5 version mismatch, but since the install is from conda forge, do you guys have any workarounds? 

Thanks,
```
A['G_iw']=S.G_iw
  File "/home/srr70/miniconda3/envs/triqs/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 194, in __setitem__
    for n,v in d.items() : SUB[n] = v
  File "/home/srr70/miniconda3/envs/triqs/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 194, in __setitem__
    for n,v in d.items() : SUB[n] = v
  File "/home/srr70/miniconda3/envs/triqs/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 184, in __setitem__
    val.__write_hdf5__(self._group,key)
TypeError: Internal error : invalid id from h5py !
```

conda list

```
# packages in environment at /home/srr70/miniconda3/envs/triqs:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
apipkg                    1.5                        py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports_abc             0.5                        py_1    conda-forge
binutils_impl_linux-64    2.34                 h2122c62_8    conda-forge
binutils_linux-64         2.34                h47ac705_21    conda-forge
boost-cpp                 1.72.0               h8e57a91_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
contextlib2               0.6.0.post1                py_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
execnet                   1.7.1                      py_0    conda-forge
fftw                      3.3.8           mpi_openmpi_h6dd7431_1011    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
funcsigs                  1.0.2                      py_3    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
futures                   3.3.0            py27h8c360ce_1    conda-forge
gcc_impl_linux-64         7.5.0               hda68d29_10    conda-forge
gcc_linux-64              7.5.0               ha781d05_21    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
gxx_impl_linux-64         7.5.0               h64c220c_10    conda-forge
gxx_linux-64              7.5.0               ha781d05_21    conda-forge
h5py                      2.10.0          nompi_py27h513d04c_102    conda-forge
hdf5                      1.10.5          mpi_openmpi_hac320be_1004    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
kernel-headers_linux-64   2.6.32              h77966d4_12    conda-forge
kiwisolver                1.1.0            py27h9e3301b_1    conda-forge
ld_impl_linux-64          2.34                 hc38a660_8    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libclang                  10.0.1          default_hde54327_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0               hdf63c60_10    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_0    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
linecache2                1.0.0                      py_1    conda-forge
mako                      1.1.0                      py_0    conda-forge
markupsafe                1.1.1            py27hdf8410d_1    conda-forge
matplotlib-base           2.2.5            py27h250f245_1    conda-forge
mock                      2.0.0                 py27_1001    conda-forge
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.0.3            py27h9ab638b_1    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
nfft                      3.5.1                h46ee950_0    conda-forge
numpy                     1.16.5           py27h95a1406_0    conda-forge
openmpi                   4.0.4                hdf1f1ad_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
path.py                   10.3.1                   py27_0    conda-forge
pbr                       5.4.5              pyh9f0ad1d_0    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pytest                    3.2.2                      py_0    conda-forge
pytest-shutil             1.7.0                      py_0    conda-forge
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
scipy                     1.2.1            py27h921218d_2    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
singledispatch            3.4.0.3               py27_1000    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.32.3               hcee41ef_1    conda-forge
subprocess32              3.5.4            py27h516909a_0    conda-forge
sysroot_linux-64          2.12                h77966d4_12    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   5.1.1           py27h14c3975_1000    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
triqs                     2.2.2            py27ha6da3d6_3    conda-forge
triqs_cthyb               2.2.1            py27h4ff3246_1    conda-forge
triqs_dft_tools           2.2.1            py27h490b6c0_2    conda-forge
triqs_tprf                2.2.0            py27h8c711b1_2    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Comment by Wentzell** [comment] 2020-08-03 19:15
I am closing this as a duplicate of https://github.com/conda-forge/triqs-feedstock/issues/12

**Closed as completed by Wentzell** 2020-08-03 19:15 UTC
