### ISSUE TITLE
Make complex operators real if imaginary part is small

### ISSUE THREAD

**Issue by mzingl** [TRIQS/triqs#364] opened 2016-11-03 08:36 UTC
Hi!
When constructing our Hamiltonians we sometimes end up in case where we have complex coefficients which have only a very small imaginary part (< 1e-10). 
To have only real coefficients Gernot wrote a little function in python:
```
def make_operator_real(H):
    H2 = Operator()
    for term in H:
        h = Operator()+1
        for el in term[0]:
            if el[0]:
                h = h*c_dag(*el[1])
            else:
                h = h*c(*el[1])
        if abs(term[1].imag) > 1e-8:
            print 'WARNING: Imaginary part larger than 1e-8'     
        H2 = H2 + term[1].real*h
    return H2  
```
It would be nice to have such a function directly in TRIQS. Maybe it is even possible to automatically convert to real coefficients if the imaginary parts are tiny.

Thanks.

**Comment by parcollet** [comment] 2016-11-03 16:26
I agree.
Should be a method .real() in the operator class ?
@krivenko : opinion ?

**Comment by krivenko** [comment] 2016-11-03 17:23
I don't mind adding `real()` and `imag()`, but rather as free functions, just as we did with `dagger()`.
Should it be done on the C++ level?

**Comment by parcollet** [comment] 2016-11-03 17:25
I guess so, and wrapped.

**Comment by parcollet** [comment] 2016-11-03 17:34
wrapped as a method

**Comment by mferrero** [comment] 2016-11-03 20:14
I also think it would be best to avoid an automatic conversion (as proposed by Manuel) to avoid unexpected behaviour. Do you agree?

**Comment by parcollet** [comment] 2016-11-03 20:15
Sure !
Explicit is better than implicit

**Comment by mzingl** [comment] 2016-11-04 07:38
My idea to "correct" operators automatically is coming from this:
`print 1e-14*c_dag(1,0)`
which is automatically set to 0. Should this also be explicit?

In the end such terms or terms with small imaginary part are always coming from numerical inaccuracies. Therefore, at least the solver should automatically throw away coefficients which are small and convert coefficients to real if the imaginary part is small.

**Comment by krivenko** [comment] 2016-11-09 19:21
> My idea to "correct" operators automatically is coming from this:
> `print 1e-14*c_dag(1,0)`
> which is automatically set to 0. Should this also be explicit?

Now, your comment makes me think that only `0*c_dag(1,0)` must be converted to 0...

Anyhow, I shall add `real()`, `imag()` and a pure Python function similar to `make_operator_real`, maybe with an extra tolerance argument.

**Comment by krivenko** [comment] 2016-11-10 01:14
Here you go!
Check this [commit](https://github.com/TRIQS/triqs/commit/14f3eb8b7dbbbbd37936c491cea6410e0c17d8d2) and tell me if you need anything else.

**Comment by mzingl** [comment] 2016-11-10 08:35
Works!
Thanks for the prompt implementation and I think we can close this if everyone is fine with the solution.

**Comment by francescopt** [comment] 2016-11-16 13:39
Hi,
I add a comment here because it is a rather similar issue.
I found useful for my purposes to have a function which iterates over the coefficients of a `many_body_operator_generic`, applying a given function to the coefficient. See the following code, inserted inside the definition of the `many_body_operator_generic` class:
```

  template <typename Lambda>
    friend many_body_operator_generic foreachcoef(many_body_operator_generic const& op, Lambda L) {
    many_body_operator_generic res;
    for (auto const& x : op)
      res.monomials.insert({x.monomial, L(x.coef)});
    return res;
  }

```

The function `foreachcoef` accept a function `L` and returns the `many_body_operator_generic` where each coefficient `coef` is replaced by `L(coef)`.
As far as I understand, one has to implement such a function as a friend inside the `many_body_operator_generic` class, otherwise one does not have write access to `monomials`.

Francesco

**Comment by parcollet** [comment] 2017-06-25 11:33
@krivenko : is this issue still open ?

**Comment by mzingl** [comment] 2017-06-25 12:40
From my side this can be closed.

**Comment by parcollet** [comment] 2017-06-25 19:33
@krivenko : can we close it ?

**Comment by krivenko** [comment] 2017-06-25 19:43
Give me a couple of hours to make a decision...

**Comment by krivenko** [comment] 2017-06-25 21:05
I am closing this issue as resolved.
Please merge #430 or continue discussing there.

**Closed by krivenko** 2017-06-25 21:05 UTC
