### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/triqs#664] opened 2018-12-29 21:28 UTC
Dear Triqs Group
Hi
I want to run dft+dmft calculation considering SO. But when I run  "case.py" for the SrVO3 compound, I have error that:
"File "case.py", line 64, in <module>
 S.solve(h_int=h_int, **p)
File "............./cthyb_solver.py", line 95, in solve
solve_status = SolverCore.solve(self, **params_kw)
.. Error .. calling C++ overload 
.. solve() -> void 
.. in implementation of method SolverCore.solve
.. C++ error was : 
.. Triqs runtime error at .........../fundamental_operator_set.hpp : 147

Operator with indices (down,0) does not belong to this fundamental set!
.. Error occurred on node 0"
can you help me to fix this error?
Thanks a lot
Reyhaneh

**Comment by mzingl** [comment] 2018-12-29 22:43
This is a duplicate of TRIQS/cthyb#101 and TRIQS/dft_tools#110.
Please close this issue.

**Closed** 2018-12-29 23:20 UTC
