### ISSUE TITLE
Tail of inverse GF

### ISSUE THREAD

**Issue by mzingl** [TRIQS/triqs#612] opened 2018-07-18 21:18 UTC
I was a bit confused with the tails of an inverse GF. 
After discussing with @parcollet I realized that one should first calculate the physical quantity, G or Sigma,  and then determine the tail parameters if desired.
This issue is a reminder that the following code, where I try to fit an inverse GF, should throw an exception:
```
import numpy as np
from pytriqs.gf import *
G_iw =  GfImFreq(indices = [0,1], beta = 50.0, n_points = 1000)
G_iw << Omega
print G_iw.fit_tail()[0]
```
Best,
Manuel

**Comment by gkraberger** [comment] 2018-08-20 10:13
Is there a way to deduce the Green's function tail parameters from the Sigma tail parameters (in the code, theoretically I know that it is possible) and vice versa? Would that feature be good to have/relevant?

**Comment by Wentzell** [comment] 2018-11-15 20:46
Hey Manuel

> This issue is a reminder that the following code, where I try to fit an inverse GF, should throw an exception

This is not quite the intended behavior. Instead we want to get a sizeable error on the tail-fit procedure such that operations like the Fourier Transform can throw in that case.

With the recent updates to unstable this is now fixed. Cf. https://github.com/TRIQS/triqs/blob/f23f1aa27c0321472bd8929cb2c049de49f36824/test/pytriqs/base/tail_issues.py#L13-L20

**Closed by Wentzell** 2018-11-15 20:46 UTC
Labels: Tail
