### ISSUE TITLE
run triqs code 1

### ISSUE THREAD

**Issue by ghragoozloo** [TRIQS/triqs#495] opened 2017-10-12 14:07 UTC
Hi all
I am getting a error message when running the following code in a pytriqs Ce-gamma.py :

[hadi@localhost NiO]$ pytriqs Ce-gamma.py
Starting on 1 Nodes at : 2017-10-11 02:20:50.794648
Reading input from NiO.ctqmcout...
Reading input from NiO.symqmc...
Reading input from NiO.oubwin...
Reading input from NiO.struct...
Reading input from NiO.outputs...
Dichotomy adjustment of Chemical Potential to obtain Total Density = 13.992000 +/- 0.000001
Chemical Potential = -0.500000
Total Density = 12.871273
0.000000 < Chemical Potential < -0.500000
14.077033 < Total Density < 12.871273
-0.035261 < Chemical Potential < -0.500000
14.052415 < Total Density < 12.871273
-0.059032 < Chemical Potential < -0.500000
14.022850 < Total Density < 12.871273
-0.070846 < Chemical Potential < -0.500000
14.003540 < Total Density < 12.871273
-0.075220 < Chemical Potential < -0.500000
13.995464 < Total Density < 12.871273
-0.076528 < Chemical Potential < -0.500000
13.992940 < Total Density < 12.871273
-0.076883 < Chemical Potential < -0.500000
13.992247 < Total Density < 12.871273
-0.076977 < Chemical Potential < -0.500000
13.992064 < Total Density < 12.871273
-0.077001 < Chemical Potential < -0.500000
13.992017 < Total Density < 12.871273
-0.077007 < Chemical Potential < -0.500000
13.992004 < Total Density < 12.871273
-0.077009 < Chemical Potential < -0.500000
13.992001 < Total Density < 12.871273
-0.077009 < Chemical Potential < -0.500000
13.992000 < Total Density < 12.871273
Chemical Potential found in 12 iterations :
Total Density = 13.992000;Chemical Potential = -0.077009
Traceback (most recent call last):
File "Ce-gamma.py", line 71, in 
S.G <<= SK.extract_G_loc()[0]
File "/home/hadi/triqs/install/lib/python2.7/site-packages/pytriqs/gf/local/block_gf.py", line 257, in ilshift
for (i,g) in self: g.copy_from(A[i])
RuntimeError: .. Error occurred at Wed Oct 11 02:21:21 2017

.. Error .. calling C++ overload
.. copy_from(gf_view<imfreq,matrix_valued,tail> other) -> void
.. in implementation of method GfImFreq.copy_from
.. C++ error was :
.. Triqs runtime error at /home/hadi/triqs/triqs.src/triqs/./gfs/./impl/../singularity/tail.hpp : 306

tails are incompatible
.. Error occurred on node 0

[hadi@localhost NiO]$

**Comment by HugoStrand** [comment] 2017-10-12 14:45
Dear all, 

I do not know what is going wrong here but this is a standard script from `dft_tools` see

https://triqs.ipht.cnrs.fr/1.x/applications/dft_tools/guide/images_scripts/Ce-gamma_script.html#ce-gamma-script

what breaks is a greens function assignment from a `sumkdft` object to a hubbard one solver.

```python
S.G <<= SK.extract_G_loc()[0]
```
The rest is guessing. Is this a known issue?

@ghragoozloo to be able to understand what is going wrong it would be good with more information.

What branch of `triqs`, `hubbard_I`, and `dft_tools` are you using?
Are the tests of `dft_tools` and `triqs` passing without errors on your system?

Best regards,
Hugo

**Comment by mzingl** [comment] 2017-10-12 19:31
Dear all,

if I am right, you are trying to use the Ce-gamma script with the Hubbard-I solver for NiO. 
The issue is that you are using only the e_g orbitals of NiO as correlated subspace (as specified in NiO.indmftpr). However, the Hubbard-I solver requires to treat the full d-subspace.
Try to modify the NiO.indmftpr file to 
```2                ! Nsort
1 1              ! Mult(Nsort)
3                ! lmax
cubic            ! choice of angular harmonics
0 0 2 0          ! l included for each sort
0 0 0 0          ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
0
cubic            ! choice of angular harmonics
0 1 0 0          ! l included for each sort
0 0 0 0          ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
-1.0 1.0         ! Ni d bandwidth
```
Make sure to select a meaningful bandwidth (last line), I just used a very large window here.

I tried it myself with the newest master versions. The Ce-gamma script is working for NiO and also for Ce. On a side note, be careful when using a Hubbard-I solver, as it is a rather crude approximation.

Best,
Manuel

**Comment by aichhorn** [comment] 2017-11-02 09:41
Issue now appeared also on the dfttools issues list. Closing here.

**Closed by aichhorn** 2017-11-02 09:41 UTC
