### ISSUE TITLE
Multiple FT crashes TRIQS

### ISSUE THREAD

**Issue by mzingl** [TRIQS/triqs#606] opened 2018-07-11 16:17 UTC
```
from` pytriqs.gf import GfImFreq, iOmega_n, inverse
# GF
g = GfImFreq(indices = [0], beta = 200, n_points = 1000)
gt = GfImTime(indices = [0], beta = 200)
a = 2.0
g << inverse( iOmega_n + a)
# Do FT multiple times 
it = 200
# err measures how well G_ij(iw) = G*_ij(-iw) is fullfilled
err = np.zeros(it)
for i in range(it):
    gt << InverseFourier(g)
    g << Fourier(gt)
    err[i] = np.linalg.norm(g.data[0,:,:] - np.transpose(np.conj(g.data[-1,:,:])))
print g.data[0,:,:] - np.transpose(np.conj(g.data[-1,:,:]))
print err
```

Code crashes  with ERROR: Inverse Fourier implementation requires vanishing 0th moment
Also: err is growing with i

**Comment by mzingl** [comment] 2018-07-11 20:18
This is an issue of growing numerical errors. Probably difficult to avoid.

**Comment by gkraberger** [comment] 2018-07-12 07:53
Hi Manuel,

Sorry to resuscitate a closed thread, but this looks like a regression to me.

I tried the same code once with TRIQS 1.5, with that I can run for 10000 iterations and get an error in the range of 10^-12. With TRIQS 2.0, it indeed crashes after the 200th iteration with the error you mentioned.

**Comment by mferrero** [comment] 2018-07-12 09:42
Can you try to make the number of frequencies larger, say 5000 instead of 1000?

**Comment by gkraberger** [comment] 2018-07-12 10:38
When I use a higher number for the number of Matsubara frequencies in that test, the error in TRIQS 2.0 occurs earlier: E.g. with n_points=2000 after the 6th and with n_points=3000 already after the first iteration (i.e., when hitting ``gt << InverseFourier(g)`` for the 2nd time).

**Comment by mzingl** [comment] 2018-07-12 11:02
Don't you also see err growing with i in TRIQS 1.5? My conclusion yesterday was that this was always happening on gf.data. Now with the new Tail the 0th moment is checked, but this check was not done before.

**Comment by gkraberger** [comment] 2018-07-12 11:12
Yes, the error grows. But in TRIQS 1.5 the tail moments were not affected by that because they did not change. The 0th moment stays exactly zero all the time. Only in TRIQS 2.0 the tail moments change and thus at some point the 0th moment is > than the threshold, which gives the error.

**Comment by gkraberger** [comment] 2018-08-20 08:58
A somewhat related issue:

when adding noise to a GfImTime, the inverse Fourier routine throws an error because the error of the tail moments become too big.

```
try:
    from pytriqs.gf import *
    GfImFreq
except:
    from pytriqs.gf.local import *
import numpy as np

noise = 1e-3

G_iw = GfImFreq(beta=10, indices=[0, 1])
G_iw[1, 1] << (4.0 * Flat(0.4) - 2.0 * Flat(0.2)) / 2.0
G_iw[0, 0] << (8.0 * Flat(0.8) - 2.0 * Flat(0.2)) / 6.0

# Generate G_tau_noise
np_tau = len(G_iw.mesh) + 1
G_tau = GfImTime(beta=G_iw.mesh.beta, indices=[0, 1],
                 n_points=np_tau)
G_tau.set_from_inverse_fourier(G_iw)
# add some noise to G_tau
np.random.seed(666)
G_tau_noise = G_tau.data + noise * np.random.randn(*np.shape(G_tau.data))
# Symmetrize G_tau_noise
G_tau_noise[:, 0, 1] = G_tau_noise[:, 1, 0].conjugate()

# put it back into TRIQS G_tau and G_iw
G_tau.data[:,:,:] = G_tau_noise[:,:,:]
G_iw.set_from_fourier(G_tau)
G_tau.set_from_inverse_fourier(G_iw)
print(np.max(np.abs(G_tau.data - G_tau_noise)))
```

The behavior is as follows:
- In TRIQS 2.0, an error is thrown 
```
Traceback (most recent call last):
  File "test1.py", line 28, in <module>
    G_tau.set_from_inverse_fourier(G_iw)
  File "/temp/AG-CMS/TRIQS/complex/new_debian/2.0/lib/python2.7/site-packages/pytriqs/gf/gf.py", line 59, in _
    return a(self, *args, **kw)
RuntimeError: .. Error occurred at Mon Aug 20 10:35:33 2018

.. Error .. calling C++ overload 
.. set_from_inverse_fourier(gf_view<imtime,matrix_valued> g_out, gf_view<imfreq,matrix_valued> g_in) -> void 
.. in implementation of function gf_fnt.set_from_inverse_fourier
.. C++ error was : 
.. Triqs runtime error at /itp/MooseFS/AG-CMS/TRIQS/complex/new_debian/2.0/src/triqs/triqs/gfs/transform/fourier_matsubara.cpp : 183

(error < 1e-3)
 ERROR: High frequency moments have an error greater than 1e-3.
  Error = 0.003473
.. Error occurred on node 
```
- In TRIQS 1.4, the code runs, but the difference between the original and the back-and-forth Fourier transformed G(tau) is 0.0005. I'm not sure if this is problematic since, anyhow, we have noise on the order of 10^-3. A quick test with different noise levels shows that the FT error is always below the noise
```
noise      FT error
1.0000e-08 5.1038e-09
1.0000e-07 5.1038e-08
1.0000e-06 5.1038e-07
1.0000e-05 5.1038e-06
1.0000e-04 5.1038e-05
1.0000e-03 5.1038e-04
1.0000e-02 5.1038e-03
```

Of course, not being able to FT noisy data (accurately) not good. However, I see the same when I try to perform the inverse Fourier transfrom of CTHYB data (i.e., trying to iFT from Solver.G_iw to a G_tau). Presumably, already G_iw is wrong, which should make us think about what we are doing in DMFT. (Of course, there we can probably live with a small error, which we will always have with QMC).

**Comment by gkraberger** [comment] 2018-08-20 09:09
Another test:

```
try:
    from pytriqs.gf import *
    GfImFreq
except:
    from pytriqs.gf.local import *
import numpy as np

N_points = 2000
G_iw = GfImFreq(beta=40, indices=[0], n_points=N_points)
G_iw << SemiCircular(1)
G_tau = GfImTime(beta=40, indices=[0], n_points=2*N_points+1)
G_tau.set_from_inverse_fourier(G_iw)

print(np.max(np.abs(G_tau.data.imag)))
```

This test with perfect data (i.e., without noise) shows that the imaginary part, which is zero, is ``6*10^-9`` in TRIQS 2.0 while it is ``2*10^-16`` in TRIQS 1.4. Being more than 7 orders of magnitude above machine accuracy for doubles is not good.

**Comment by Wentzell** [comment] 2019-01-10 16:53
Thank you @mzingl and @gkraberger for pointing out these issues.
They have been resolved in the latest triqs/unstable and I have gathered all problems in the
new test [tail_issues](https://github.com/TRIQS/triqs/blob/master/test/pytriqs/base/tail_issues.py).

In particular consider the [multi_fft](https://github.com/TRIQS/triqs/blob/8f28b709526b3260aedb89a6380773733ca90d33/test/pytriqs/base/tail_issues.py#L28-L51) and [noisy_gf](https://github.com/TRIQS/triqs/blob/8f28b709526b3260aedb89a6380773733ca90d33/test/pytriqs/base/tail_issues.py#L126-L159) subtests.

**Closed by Wentzell** 2019-01-10 16:53 UTC
Labels: Tail
