### ISSUE TITLE
assert_block_gfs_are_close block order

### ISSUE THREAD

**Issue by gkraberger** [TRIQS/triqs#349] opened 2016-07-27 08:36 UTC
Hi,

how is `assert_block_gfs_are_close` be supposed to behave if the order of two blocks is reversed?

E.g.:

```
from pytriqs.gf.local import *
from pytriqs.utility.comparison_tests import *
a = GfImFreq(beta=40,indices=[0])
b = GfImFreq(beta=40,indices=[0])
a << inverse(iOmega_n - 1)
b << inverse(iOmega_n - 2)
B1 = BlockGf(name_list=['a','b'],block_list=[a,b])
B2 = BlockGf(name_list=['b','a'],block_list=[b,a])
assert_block_gfs_are_close(B1,B2)
```
This throws an error.

If I use
```
B1 = BlockGf(name_list=['a','b'],block_list=[a,b])
B2 = BlockGf(name_list=['b','a'],block_list=[a,b])
```
it passes although the names don't match.

Physically the order of the blocks shouldn't matter; often (e.g. in the CTHYB solver) the BlockGf is constructed from a dictionary (gf_struct), where the order of the entries is not defined in python.

Thus, I believe that blocks with the same name should be compared and not blocks with the same "index".

**Comment by krivenko** [comment] 2016-07-31 10:01
Looks like a Python incarnation of #342.

**Comment by parcollet** [comment] 2016-07-31 10:03
It is.
The problem is that there is no good solution to this

**Comment by tayral** [comment] 2016-08-02 14:19
It is a reincarnation of #342 : closing (--> see #342 for updates)

**Closed by tayral** 2016-08-02 14:19 UTC
